# Generated by Django 5.2.4 on 2025-07-30 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('formateur', 'Formateur'), ('admin', 'Administrateur')], default='etudiant', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('formateur', models.ForeignKey(blank=True, limit_choices_to={'role': 'formateur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_enseignes', to='user.profile')),
            ],
            options={
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Valeur de la note (par exemple, 15.75)', max_digits=5)),
                ('date_publication', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la publication de la note')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_du_cours', to='user.cours')),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes_recues', to='user.profile')),
                ('publie_par', models.ForeignKey(blank=True, help_text='Le formateur qui a publié cette note', limit_choices_to={'role': 'formateur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_publiees', to='user.profile')),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'ordering': ['-date_publication'],
                'unique_together': {('etudiant', 'cours')},
            },
        ),
    ]
