# Generated by Django 5.2.4 on 2025-07-31 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la Promotion')),
                ('year', models.IntegerField(verbose_name='Année de la Promotion')),
            ],
            options={
                'verbose_name_plural': 'Promotions',
                'ordering': ['year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la Spécialité')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la Spécialité')),
            ],
            options={
                'verbose_name_plural': 'Spécialités',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['nom'], 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profils'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='commentaire',
        ),
        migrations.AlterField(
            model_name='cours',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description Détaillée'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='formateur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'formateur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_enseignes', to='user.profile', verbose_name='Formateur Associé'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du Cours'),
        ),
        migrations.AlterField(
            model_name='note',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_du_cours', to='user.cours', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, help_text='Date et heure auxquelles la note a été publiée', verbose_name='Date de Publication'),
        ),
        migrations.AlterField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(limit_choices_to={'role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes_recues', to='user.profile', verbose_name='Étudiant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='publie_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['formateur', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_publiees', to='user.profile', verbose_name='Publiée Par'),
        ),
        migrations.AlterField(
            model_name='note',
            name='valeur',
            field=models.DecimalField(decimal_places=2, help_text='Valeur numérique de la note (ex: 15.75)', max_digits=5, verbose_name='Valeur de la Note'),
        ),
        migrations.AddField(
            model_name='cours',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='user.promotion', verbose_name='Promotion du Cours'),
        ),
        migrations.AddField(
            model_name='profile',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants_profiles', to='user.promotion', verbose_name='Promotion (pour étudiant)'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='user.speciality', verbose_name='Spécialité associée'),
        ),
        migrations.AddField(
            model_name='cours',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='user.speciality', verbose_name='Spécialité du Cours'),
        ),
        migrations.AddField(
            model_name='profile',
            name='assigned_specialities',
            field=models.ManyToManyField(blank=True, related_name='assigned_formateurs', to='user.speciality', verbose_name='Spécialités assignées (pour formateur)'),
        ),
        migrations.AlterUniqueTogether(
            name='promotion',
            unique_together={('name', 'speciality')},
        ),
    ]
